export const projects = [
	{
			slug: "giantsbridge",
			highlightColor: "#FCBB6D",
			title: "GIANT'S BRIDGE",
			description: "Action-packed couch co-op",
			who: "Team of 5",
			when: "Summer 2021",
			learnMoreLink: "/projects/welcome",
			image1: "/images/iqtn52.jpg",
			image2: "/images/Dp5Cfr.jpg",
			markdown: "/markdown/text.md",
		},
		{
			slug: "fpscore",
			highlightColor: "#888888",
			title: "FPS CORE",
			description: "Open-source game development",
			who: "Solo",
			when: "September 2022 - Present",
			learnMoreLink: "/projects/welcome",
			image1: "/images/fc-1.png",
			image2: "/images/fc-2.png",
			markdown: "/markdown/text.md",
		},
		{ 
			slug: "projectisolation",
			highlightColor: "#F2BAC9",
			title: "PROJECT ISOLATION",
			description: "Open world exploration",
			who: "Solo",
			when: "August 2021 - Present",
			learnMoreLink: "/projects/welcome",
			image1: "/images/pi-1.png",
			image2: "/images/pi-2.png",
			markdown: "/markdown/text.md",
		}
];
